### ISSUE TITLE
Error : Cannot read properties of undefined (reading 'itemSettingList')

### ISSUE THREAD

**Issue by Lastnet0709** [zuydd/moonbix#2]
```
file:///moonbix/src/services/payload.js:291
      dataStart.cryptoMinerConfig.itemSettingList
                                  ^

TypeError: Cannot read properties of undefined (reading 'itemSettingList')
    at PayloadService.initItemStart (file:///moonbix/src/services/payload.js:291:35)
    at PayloadService.createPayload (file:///moonbix/src/services/payload.js:443:28)
    at GameService.completeGame (file:///moonbix/src/services/game.js:50:37)
    at GameService.handlePlayGame (file:///moonbix/src/services/game.js:113:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (file:///moonbix/src/run/index.js:120:7)
```

**Comment by yayangkasep** [comment]
same issue

**Comment by ManhVuAmela** [comment]
same issue
